version: '3'

services:

  arist_base_host:
    image: arist_base/host
    environment:
      ASPNETCORE_ENVIRONMENT: "Staging"
      ConnectionStrings__Default: "User ID=aristqnu;Password='ji1o@832!NVl1';Host=113.161.0.189;Port=8055;Database=Test;Pooling=true;"
      App__ServerRootAddress: "http://localhost:44311/"
      App__ClientRootAddress: "http://localhost:4200/"
      App__CorsOrigins: "http://localhost:4200"
      TZ: "Asia/Ho_Chi_Minh"
      Kestrel__Endpoints__Http__Url: "http://+:80"
    ports:
      - "44311:80"
    volumes:
      - "./Host-Logs:/app/App_Data/Logs"
    restart: always

  arist_base_ng:
    image: arist_base/ng
    ports:
      - "4200:80"
